bindfs_paths:
  /var/aegir/platforms: platforms
  /var/aegir/config/valkyrie_aliases: .valkyrie/cache/aliases
  /var/aegir/.cache/site_repos: .valkyrie/cache/site_repos
dot_files:
  - .gitconfig
  - .vimrc
  - .bashrc
ip: 10.42.0.10
tld: val
name: valkyrie
use_vagrant_dns: TRUE
use_vagrant_bindfs: TRUE
manage_drushrc_alias_path: TRUE
vm_memory: 1024
vm_box: hashicorp/precise64
