---
- hosts: localhost
  vars:
    - drush_version: 8.x
    - host_uid: 1000
  pre_tasks:
    - name: Create 'aegir' user to map to host user
      user:
        name: aegir
        uid: "{{ host_uid }}"
  roles:
    - geerlingguy.mysql
    - getvalkyrie.drush
    - getvalkyrie.valkyrie
    - geerlingguy.java
    - getvalkyrie.selenium
    - getvalkyrie.drulenium
    - getvalkyrie.aegir3drulenium
#    - getvalkyrie.aegir3platforms
    - { role: getvalkyrie.aegir3platforms, platform_name: getopenoutreach, makefiles_repo: "https://github.com/PraxisLabs/getopenoutreach_makefiles.git", makefile_name: getopenoutreach.make, release_feed: "https://github.com/PraxisLabs/getopenoutreach_makefiles/releases.atom", tags: auto-deploy }
    - { role: getvalkyrie.aegir3platforms, platform_name: openatrium, makefiles_repo: "http://git.drupal.org/project/openatrium.git", makefile_name: build-openatrium.make, release_feed: "https://www.drupal.org/node/681432/release/feed", tags: auto-deploy }
    - { role: getvalkyrie.aegir3platforms, platform_name: civicrm, makefiles_repo: "https://github.com/PraxisLabs/civicrm_makefiles.git", makefile_name: build-civicrm.make, release_feed: "https://github.com/PraxisLabs/civicrm_makefiles/tags.atom", tags: auto-deploy }
    - { role: getvalkyrie.aegir3platforms, platform_name: drulenium, makefiles_repo: "https://github.com/ErgonLogicEnterprises/hosting_drulenium_drupal7_makefiles.git", makefile_name: hosting_drulenium_drupal7_makefiles.make, release_feed: "https://github.com/ErgonLogicEnterprises/hosting_drulenium_drupal7_makefiles/tags.atom", tags: auto-deploy }
# broken
#- hosts: auto-deploy-rune
#  become: yes
#  roles:
#    - { role: ansible-role-aegir3platforms, platform_name: rune, makefiles_repo: "https://github.com/poetic/rune.git", makefile_name: makefiles/stubs/build.make.yml, release_feed: "https://github.com/poetic/rune/tags.atom", tags: auto-deploy }
# drush dl needs own role
#- hosts: ansible-role-aegir3platforms
#  become: yes
#  roles:
#    - { role: ansible-role-aegir3platforms}
# broken php7
    - { role: getvalkyrie.aegir3platforms, platform_name: drupal8, makefiles_repo: "https://github.com/PraxisLabs/drupal8_makefiles.git", makefile_name: drupal8.make, release_feed: "https://github.com/PraxisLabs/drupal8_makefiles/tags.atom", tags: auto-deploy }
# ansible-playbook i inventory site.yml --connection=local --sudo -vvvv
