---
- hosts: localhost
  vars:
    - drush_version: 8.x
    - host_uid: 1000
  pre_tasks:
    - name: Create 'aegir' user to map to host user
      user:
        name: aegir
        uid: "{{ host_uid }}"
  roles:
    - geerlingguy.java
    - getvalkyrie.selenium
    - geerlingguy.mysql
    - getvalkyrie.drush
    - getvalkyrie.valkyrie
    - getvalkyrie.drulenium
    - getvalkyrie.aegir3drulenium
#    - getvalkyrie.aegir3platforms
